-- Snowflake Portfolio Project
-- Environment setup

CREATE DATABASE IF NOT EXISTS PORTFOLIO_DB;

CREATE SCHEMA IF NOT EXISTS PORTFOLIO_DB.RAW;
CREATE SCHEMA IF NOT EXISTS PORTFOLIO_DB.ANALYTICS;

USE WAREHOUSE COMPUTE_WH;
USE DATABASE PORTFOLIO_DB;
USE SCHEMA RAW;

-- Keep compute costs low
ALTER WAREHOUSE COMPUTE_WH
SET AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;